### PR TITLE
fix(setup ci|cd): setup ci|cd pipelines

### PR DESCRIPTION
**Pull request by torsami77**
#### What does this PR do?
- fixes setup ci|cd pipelines

#### Description of Task to be completed?
- find heroku log
- configures package.json
- configures .travis.yml

#### How should this be manually tested?
- Check heroku staging - https://staged-team-010-backend.herokuapp.com/
- check travisCI build - https://travis-ci.com/github/BuildForSDG/team-010-backend/builds/166455125
- check coveralls coverage - https://coveralls.io/github/BuildForSDG/team-010-backend

#### Any background context you want to provide?
- Please take note that all test env variable would henceforth be added on .travis.yml file
- ignore the currently unkown badges on the branch, the badges can only reflect the develop branch which would begin after merge

#### Questions:

### CODE REVIEW

**Review by RuthChisom — DISMISSED** [review]

**Review by Biosmatrix — CHANGES_REQUESTED** [review]
Hi @torsami77 you have done a nice work here, kindly remove sequelize-test-helpers and parcel-bundler  from the package.json file since we not use it for the project

**Comment by torsami77** [comment]
> Hi @torsami77 you have done a nice work here, kindly remove sequelize-test-helpers and parcel-bundler from the package.json file since we not use it for the project

Thanks for pointing those out bro, would effect those changes soon

**Comment by Biosmatrix** [comment]
@torsami77 also add the build folder to gitignore file as it is not necessary to push it to the repo

**Review by RuthChisom — DISMISSED** [review]
Approve

**Review by RuthChisom — DISMISSED** [review]
Approve!!

**Review by Biosmatrix — CHANGES_REQUESTED** [review]
@torsami77 well done, however there are few things i want you to fix
1. add a forward slash / to build in line 2 @ .gitignore file to exclude it from git
2. Move the nodemon package to devDependencies
3. Remove the nyc package as it is not being used
4. add a .env.example with some examples of the config used for the project

**Review by Biosmatrix — DISMISSED** [review]
Approved

**Review by WillDera — DISMISSED** [review]
Approved

**Review by RuthChisom — APPROVED** [review]
Approve!

**Review by Biosmatrix — COMMENTED** [review]
@torsami77 well done looks good

**Review by Biosmatrix — APPROVED** [review]
Approved

**Review by WillDera — APPROVED** [review]
Ok.

**Pull request merged**
