### PR TITLE
#612618695 create project scaffolding

### LINKED ISSUE #3: [CHORE] Project Scaffolding
Setup basic project structure

Setup Babel and EsLint including necessary dependencies

Setup testing with Jest

Setup PostgresSQL for database

Setup Heroku deployment

### PR DESCRIPTION
**Pull request by DevGbolade**
## Description
created the Project structure and added  basic configurations

Fixes #(issue number 612618695) 

## How Has This Been Tested?
No test has been done yet as this is just the initial setup

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by RuthChisom — DISMISSED** [review]
Look good to me

**Review by RuthChisom — APPROVED** [review]
All checks passed

**Review by Biosmatrix — APPROVED** [review]
Approved

**Review by WillDera — APPROVED** [review]
Good.

**Pull request merged**
